# -*- Mode: YAML; tab-width: 4; indent-tabs-mode: nil; coding: utf-8; -*-
# vim:set ft=yaml ts=4 sw=4 sts=4 autoindent:
#
# YAML Configuration file for brat.nlplab.com
#
# Note: You need to restart Jekyll for ANY changes to take place.

### Jekyll configuration

auto:       true
markdown:   maruku
permalink:  date
pygments:   true
safe:       true
server:     true

source:     site

### Website configuration

dist:
    # Sadly, YAML doesn't do string concatenation, so you will have to do
    #   some additional typing
    release_dir_url: 'http://weaver.nlplab.org/~brat/releases'
    # Note: Change the below line(s) when releasing a new stable version
    latest_stable_tgz: 'brat-v1.3_Crunchy_Frog.tar.gz'
    latest_stable: 'brat-v1.3_Crunchy_Frog'
    demo_url: 'http://weaver.nlplab.org/~brat/demo'
